import type { NeedCard } from './api'

export const SEED_NEEDCARDS: NeedCard[] = [
  {
    id: 'seed_nc_001',
    need_type: 'rescue',
    description_clean: 'Three people trapped on rooftop at 45 MG Road after flood waters rose. Ground floor submerged. No food or water for 8 hours.',
    urgency_score_base: 9.5,
    urgency_score_eff: 9.2,
    urgency_reasoning: 'Life threat: people stranded with rising water for 8+ hours.',
    affected_count: 3,
    skills_needed: ['search_rescue', 'logistics_boat_operator'],
    geo_lat: 22.572, geo_lng: 88.363,
    geo_confidence: 0.92,
    location_text_raw: '45 MG Road, near old post office, Ward 3',
    contact_name: 'Priya Sharma', contact_detail: '9876543210',
    report_count: 2, status: 'open', needs_review: false, extraction_failed: false,
    created_at: new Date(Date.now() - 25 * 60000).toISOString(),
    updated_at: new Date(Date.now() - 10 * 60000).toISOString(),
  },
  {
    id: 'seed_nc_002',
    need_type: 'medical',
    description_clean: 'Pregnant woman in labour, hospital road blocked by flooding. No doctor on site. Situation critical.',
    urgency_score_base: 9.8,
    urgency_score_eff: 9.6,
    urgency_reasoning: 'Imminent childbirth with no medical support. Highest urgency.',
    affected_count: 1,
    skills_needed: ['medical_doctor', 'medical_nurse', 'logistics_driver'],
    geo_lat: 22.601, geo_lng: 88.379,
    geo_confidence: 0.88,
    location_text_raw: 'Near Andheri East railway crossing',
    contact_name: 'Rajan Das', contact_detail: '9765432100',
    report_count: 1, status: 'open', needs_review: false, extraction_failed: false,
    created_at: new Date(Date.now() - 12 * 60000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 60000).toISOString(),
  },
  {
    id: 'seed_nc_003',
    need_type: 'food',
    description_clean: '40 families in Ward 12 have had no food for 2 days. Children and elderly badly affected. Dry rations needed urgently.',
    urgency_score_base: 7.5,
    urgency_score_eff: 6.9,
    urgency_reasoning: '40 families, 2 days without food, children involved — serious but not immediately fatal.',
    affected_count: 40,
    skills_needed: ['food_distribution'],
    geo_lat: 22.556, geo_lng: 88.347,
    geo_confidence: 0.85,
    location_text_raw: 'Ward 12, near government school',
    contact_name: 'Ramesh Kumar', contact_detail: '9887654321',
    report_count: 7, status: 'open', needs_review: false, extraction_failed: false,
    created_at: new Date(Date.now() - 3 * 3600000).toISOString(),
    updated_at: new Date(Date.now() - 20 * 60000).toISOString(),
  },
  {
    id: 'seed_nc_004',
    need_type: 'water',
    description_clean: 'Drinking water supply contaminated after flooding. 55 people affected, children showing diarrhoea symptoms.',
    urgency_score_base: 8.5,
    urgency_score_eff: 7.8,
    urgency_reasoning: 'Water-borne illness developing in children. Urgent purification needed.',
    affected_count: 55,
    skills_needed: ['water_purification', 'water_distribution'],
    geo_lat: 22.589, geo_lng: 88.402,
    geo_confidence: 0.78,
    location_text_raw: 'Mirpur Block D, House 15',
    contact_name: 'Meena Ghosh', contact_detail: '9001234567',
    report_count: 3, status: 'open', needs_review: false, extraction_failed: false,
    created_at: new Date(Date.now() - 1.5 * 3600000).toISOString(),
    updated_at: new Date(Date.now() - 30 * 60000).toISOString(),
  },
]